services:
  - type: web
    name: careercraft-backend
    env: node
    plan: free
    buildCommand: npm run build && npm run verify
    startCommand: npm start
    nodeVersion: 18.x
    buildFilter:
      paths:
        - src/**/*.ts
        - package.json
        - tsconfig.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MAGICAL_API_KEY
        sync: false
      - key: MAGICAL_REVIEW_URL
        value: https://gw.magicalapi.com/resume-review
      - key: MAGICAL_SCORE_URL
        value: https://gw.magicalapi.com/resume-score
      - key: RAPIDAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APPWRITE_PROJECT_ID
        sync: false
      - key: APPWRITE_API_KEY
        sync: false
      - key: APPWRITE_ENDPOINT
        value: https://fra.cloud.appwrite.io/v1
      - key: APPWRITE_BUCKET_ID
        sync: false